
services:
  app:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 'True'
    volumes:
      - .:/app
      - ./mysite/staticfiles:/app/mysite/staticfiles
    depends_on:
      - db
      - elasticsearch  # Добавлен Elasticsearch

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: novamedika
      POSTGRES_PASSWORD: novamedika
      POSTGRES_DB: novamedikapostgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для сохранения данных при перезапуске контейнера

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./mysite:/app/mysite
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mysite/staticfiles:/static  # Доступ к статическим файлам
    depends_on:
      - app

volumes:
  postgres_data:

