# Generated by Django 5.1.7 on 2025-03-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_order_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sent',
            new_name='processed',
        ),
    ]
