# Generated by Django 5.1.7 on 2025-03-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_rename_sent_order_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
