# Generated by Django 4.2.20 on 2025-03-24 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0006_pharmacy_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="form",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
