# Generated by Django 4.2.20 on 2025-03-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0008_pharmacy_pharmacies__slug_ace06e_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="pharmacy_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
